general {
    hide_cursor = true
}

background {
    monitor =
    color = rgb(20, 22, 30)
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    placeholder_text = Passwort…
    fade_on_empty = true
}

label {
    monitor =
    text = $TIME
    font_size = 56
    position = 0, 160
    halign = center
    valign = center
}
