# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-5f698157-cc29-4ea1-aeb4-19a2e8df49b4";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5f698157-cc29-4ea1-aeb4-19a2e8df49b4".device = "/dev/disk/by-uuid/5f698157-cc29-4ea1-aeb4-19a2e8df49b4";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1E32-9A8C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c4a0a35b-8745-4d8c-a95e-cbc0af4e8310"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
